[package]
name = "v1"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
mysql = "22.1.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
futures = "0.3.21"
derive_more = "0.99.17"
